Traceback (most recent call last):
  File "/home/orestas41/miniconda3/envs/mlflow-fe275cdffdb91d423bbbc9efcaa0b6a9fba88e1b/lib/python3.10/site-packages/pandas/core/tools/datetimes.py", line 510, in _to_datetime_with_format
    values, tz = conversion.datetime_to_datetime64(arg)
  File "pandas/_libs/tslibs/conversion.pyx", line 360, in pandas._libs.tslibs.conversion.datetime_to_datetime64
TypeError: Unrecognized value type: <class 'str'>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/orestas41/project-FootballPredict/lithuanian-football-league-predictor/pre-processing/run.py", line 185, in <module>
    go(args)
  File "/home/orestas41/project-FootballPredict/lithuanian-football-league-predictor/pre-processing/run.py", line 65, in go
    df['Date'] = pd.to_datetime(df['Date'], format='%Y-%m-%d, %H:%M')
  File "/home/orestas41/miniconda3/envs/mlflow-fe275cdffdb91d423bbbc9efcaa0b6a9fba88e1b/lib/python3.10/site-packages/pandas/core/tools/datetimes.py", line 1051, in to_datetime
    values = convert_listlike(arg._values, format)
  File "/home/orestas41/miniconda3/envs/mlflow-fe275cdffdb91d423bbbc9efcaa0b6a9fba88e1b/lib/python3.10/site-packages/pandas/core/tools/datetimes.py", line 394, in _convert_listlike_datetimes
    res = _to_datetime_with_format(
  File "/home/orestas41/miniconda3/envs/mlflow-fe275cdffdb91d423bbbc9efcaa0b6a9fba88e1b/lib/python3.10/site-packages/pandas/core/tools/datetimes.py", line 514, in _to_datetime_with_format
    raise err
  File "/home/orestas41/miniconda3/envs/mlflow-fe275cdffdb91d423bbbc9efcaa0b6a9fba88e1b/lib/python3.10/site-packages/pandas/core/tools/datetimes.py", line 501, in _to_datetime_with_format
    res = _array_strptime_with_fallback(
  File "/home/orestas41/miniconda3/envs/mlflow-fe275cdffdb91d423bbbc9efcaa0b6a9fba88e1b/lib/python3.10/site-packages/pandas/core/tools/datetimes.py", line 437, in _array_strptime_with_fallback
    result, timezones = array_strptime(arg, fmt, exact=exact, errors=errors)
  File "pandas/_libs/tslibs/strptime.pyx", line 150, in pandas._libs.tslibs.strptime.array_strptime
ValueError: time data '0' does not match format '%Y-%m-%d, %H:%M' (match)
                  Date Blank  ...       Away                              Location
0                    0     1  ...          4                                     5
1    2023-05-28, 17:55        ...  Panevėžys                         LFF stadionas
2    2023-05-28, 16:00        ...      Banga           Dariaus ir Girėno stadionas
3    2023-05-27, 19:00        ...  Hegelmann                         LFF stadionas
4    2023-05-27, 17:00        ...    Dainava                Šiaulių sav. stadionas
..                 ...   ...  ...        ...                                   ...
745  2021-03-12, 18:00        ...  Hegelmann  Marijampolės futbolo arenos maniežas
746  2021-03-07, 15:00        ...  Panevėžys  Marijampolės futbolo arenos maniežas
747  2021-03-06, 15:00        ...    Nevėžis  Marijampolės futbolo arenos maniežas
748  2021-03-06, 13:00        ...  Hegelmann    „Ateities“ progimnazijos stadionas
749  2021-03-05, 18:00        ...      Banga  Marijampolės futbolo arenos maniežas
[750 rows x 6 columns]