                         Date  ...  Model Performance
index                          ...
2023-05-28 17:55:00  1.685296  ...                NaN
2023-05-28 16:00:00  1.685290  ...                NaN
2023-05-27 19:00:00  1.685214  ...                NaN
2023-05-27 17:00:00  1.685207  ...                NaN
2023-05-26 18:00:00  1.685124  ...                NaN
[5 rows x 6 columns]
[34m[1mwandb[39m[22m:   4 of 4 files downloaded.
Traceback (most recent call last):
  File "/home/orestas41/project-FootballPredict/lithuanian-football-league-predictor/tour_eval_pred/run.py", line 185, in <module>
    go(args)
  File "/home/orestas41/project-FootballPredict/lithuanian-football-league-predictor/tour_eval_pred/run.py", line 150, in go
    all = pd.merge(df, df1, on=df[[
  File "/home/orestas41/miniconda3/envs/mlflow-179e34a71618ccb1126551092a7decef1effd393/lib/python3.10/site-packages/pandas/core/frame.py", line 3511, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/home/orestas41/miniconda3/envs/mlflow-179e34a71618ccb1126551092a7decef1effd393/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 5782, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/orestas41/miniconda3/envs/mlflow-179e34a71618ccb1126551092a7decef1effd393/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 5845, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['Result', 'Predictions'] not in index"
       Date  Home  Away  Prediction
0  1.685804     2    12    0.680799
1  1.685812     1    10    0.655860
2  1.685819     9     4    0.290492
3  1.685901    14    13    0.389455