[34m[1mwandb[39m[22m:   4 of 4 files downloaded.
Traceback (most recent call last):
  File "/home/orestas41/project-FootballPredict/lithuanian-football-league-predictor/tour_eval_pred/run.py", line 181, in <module>
    go(args)
  File "/home/orestas41/project-FootballPredict/lithuanian-football-league-predictor/tour_eval_pred/run.py", line 146, in go
    all = pd.merge(df, df1, on=df[[
  File "/home/orestas41/miniconda3/envs/mlflow-179e34a71618ccb1126551092a7decef1effd393/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 107, in merge
    op = _MergeOperation(
  File "/home/orestas41/miniconda3/envs/mlflow-179e34a71618ccb1126551092a7decef1effd393/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 700, in __init__
    ) = self._get_merge_keys()
  File "/home/orestas41/miniconda3/envs/mlflow-179e34a71618ccb1126551092a7decef1effd393/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 1097, in _get_merge_keys
    right_keys.append(right._get_label_or_level_values(rk))
  File "/home/orestas41/miniconda3/envs/mlflow-179e34a71618ccb1126551092a7decef1effd393/lib/python3.10/site-packages/pandas/core/generic.py", line 1848, in _get_label_or_level_values
    raise KeyError(key)
KeyError:               Date  Home  ...  Prediction  Model Performance
index                     ...
1.685296  1.685296    14  ...         NaN                NaN
1.685290  1.685290     6  ...         NaN                NaN
1.685214  1.685214    10  ...         NaN                NaN
1.685207  1.685207    13  ...         NaN                NaN
1.685124  1.685124    12  ...         NaN                NaN
[5 rows x 6 columns]